stream {
  map $ssl_preread_protocol $yurupager_8889_backend {
    "" 127.0.0.1:18889;
    default 127.0.0.1:18443;
  }

  server {
    listen 8889;
    proxy_pass $yurupager_8889_backend;
    ssl_preread on;
    proxy_connect_timeout 5s;
    proxy_timeout 600s;
  }
}
